export const CONFIG = {
    COUNTDOWN_TIME: 5,
    MAX_HISTORY_SIZE: 10,
    DEFAULT_VOLUME: 0.7,
    DEFAULT_INTENSITY: 3,
    DEFAULT_ROUNDS: 3,
    DEFAULT_ROUND_DURATION: 60,
    DEFAULT_REST_DURATION: 30,
    MIN_ROUNDS: 1,
    MAX_ROUNDS: 12,
    MIN_ROUND_DURATION: 10,
    MAX_ROUND_DURATION: 180,
    MIN_REST_DURATION: 5,
    MAX_REST_DURATION: 90
};